-- ============================================================
--  Campus Lost & Found Portal — Supabase SQL Schema
--  Course: FYBSc IT - Introduction to Programming
-- ============================================================

-- 1. Create the `items` Table
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('Lost', 'Found')),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL,
    date DATE NOT NULL,
    location TEXT NOT NULL,
    contact_name TEXT NOT NULL,
    contact_number TEXT NOT NULL,
    image_url TEXT DEFAULT '',
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Resolved')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- 3. Create Permissive Policies for Student Project (No Auth Required)
-- Allow anyone (public / anon key) to read items
CREATE POLICY "Allow public read access on items"
    ON public.items
    FOR SELECT
    USING (true);

-- Allow anyone to report a new lost/found item
CREATE POLICY "Allow public insert on items"
    ON public.items
    FOR INSERT
    WITH CHECK (true);

-- Allow anyone to mark an item as Resolved
CREATE POLICY "Allow public update on items"
    ON public.items
    FOR UPDATE
    USING (true)
    WITH CHECK (true);

-- 4. Create Storage Bucket for Uploaded Photos (Optional/Recommended)
-- Insert public bucket named 'item-images' if it doesn't already exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('item-images', 'item-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies: Allow public read & upload into 'item-images' bucket
CREATE POLICY "Allow public view for item images"
    ON storage.objects
    FOR SELECT
    USING (bucket_id = 'item-images');

CREATE POLICY "Allow public upload for item images"
    ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'item-images');

-- 5. Insert Initial Realistic Demonstration Sample Items
INSERT INTO public.items (type, name, category, description, date, location, contact_name, contact_number, image_url, status)
VALUES
    (
        'Lost',
        'Black Leather Wallet',
        'Wallets/Bags',
        'WildHorn black leather wallet containing college ID card and metro card.',
        CURRENT_DATE - INTERVAL '1 day',
        'College Canteen Table 4',
        'Rahul Sharma (FYBSc IT)',
        '9876543210',
        '',
        'Active'
    ),
    (
        'Found',
        'Blue Milton Water Bottle',
        'Personal',
        'Stainless steel blue Milton 1-litre water bottle left on the study table.',
        CURRENT_DATE,
        'Library Reading Room (2nd Floor)',
        'Priya Mehta (SYBSc IT)',
        '9123456789',
        '',
        'Active'
    ),
    (
        'Lost',
        'Casio Scientific Calculator',
        'Electronics',
        'Casio fx-991EX calculator with an IT department sticker on the back cover.',
        CURRENT_DATE - INTERVAL '2 days',
        'Computer Lab 3 (Ground Floor)',
        'Aman Verma (FYBSc IT)',
        '9000012345',
        '',
        'Active'
    ),
    (
        'Found',
        'Student ID Card & Lanyard',
        'ID/Documents',
        'First-year college identity card found near the auditorium entrance corridor.',
        CURRENT_DATE - INTERVAL '3 days',
        'Main Auditorium Corridor',
        'Sunita Rao (Security Office)',
        '9765432108',
        '',
        'Resolved'
    );
